### ISSUE TITLE
Regarding PMTD

### ISSUE THREAD

**Issue by ghost** [kapness/leetcode#1]
@kapness Hi there,
Can you tell me how can you get PMTD result? Do you only use PMTD configuration on mask-rcnn benchmark, or do you modify other things?

**Comment by kapness** [comment]
you can see other issues where the author explains implementation details.
by the way,if you want to know how to get predict box from the result of maskrcnn,you can have a look at others' forked PMTD git.
of course, you have to modify some codes in maskrcnn as the paper mentioned.
------------------ 原始邮件 ------------------
发件人: "deepseek"<notifications@github.com>;
发送时间: 2019年8月22日(星期四) 下午2:02
收件人: "kapness/leetcode"<leetcode@noreply.github.com>;
抄送: "aaaaaa"<1617498149@qq.com>;"Mention"<mention@noreply.github.com>;
主题: [kapness/leetcode] Regarding PMTD (#1)




@kapness Hi there,
 Can you tell me how can you get PMTD result? Do you only use PMTD configuration on mask-rcnn benchmark, or do you modify other things?

**Comment by ghost** [comment]
@kapness I would dare and request you to send me the modified code.
I am sure you have your own version by now.
